# Generated by Django 5.2.8 on 2025-11-26 14:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveIntegerField(help_text='Question order (1, 2, 3...)')),
                ('question_text', models.TextField(help_text='The question content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Assessment Question',
                'verbose_name_plural': 'Assessment Questions',
                'db_table': 'assessment_questions',
                'ordering': ['sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transcript', models.JSONField(default=list, help_text='Assessment conversation transcript')),
                ('is_completed', models.BooleanField(db_index=True, default=False, help_text='Whether assessment is finished')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Technical Assessment',
                'verbose_name_plural': 'Technical Assessments',
                'db_table': 'technical_assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, db_index=True, help_text='Unique session identifier', max_length=255, null=True)),
                ('messages', models.JSONField(default=list, help_text='Raw conversation messages')),
                ('extracted_info', models.JSONField(blank=True, default=dict, help_text='Extracted user data: {name, qualification, experience}')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Voice Conversation',
                'verbose_name_plural': 'Voice Conversations',
                'db_table': 'voice_conversations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(blank=True, default='NIL', help_text="Candidate's response")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.OneToOneField(help_text='The question being answered', on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='form_ai.assessmentquestion')),
            ],
            options={
                'verbose_name': 'Candidate Answer',
                'verbose_name_plural': 'Candidate Answers',
                'db_table': 'candidate_answers',
            },
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='assessment',
            field=models.ForeignKey(help_text='Parent assessment', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='form_ai.technicalassessment'),
        ),
        migrations.AddField(
            model_name='technicalassessment',
            name='conversation',
            field=models.ForeignKey(help_text='Parent conversation', on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='form_ai.voiceconversation'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentquestion',
            unique_together={('assessment', 'sequence_number')},
        ),
    ]
