# Generated by Django 5.2.8 on 2025-11-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='user_response',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
