# Generated by Django 5.2.6 on 2025-11-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalassessment',
            name='qa_snapshot',
            field=models.JSONField(blank=True, default=list, help_text='Snapshot of questions and answers'),
        ),
    ]
