# Generated by Django 5.2.6 on 2025-11-27 06:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_ai', '0002_technicalassessment_qa_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Internal name for the interview', max_length=255)),
                ('role', models.CharField(blank=True, help_text='Role or track this interview targets (e.g., Python Intern)', max_length=255)),
                ('summary', models.TextField(blank=True, help_text='Short description shown on the builder page')),
                ('ai_prompt', models.TextField(blank=True, help_text='Optional custom instructions appended to the base AI persona')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Interview Form',
                'verbose_name_plural': 'Interview Forms',
                'db_table': 'interview_forms',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='technicalassessment',
            name='interview_form',
            field=models.ForeignKey(blank=True, help_text='Interview template that supplied the questions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='form_ai.interviewform'),
        ),
        migrations.AddField(
            model_name='voiceconversation',
            name='interview_form',
            field=models.ForeignKey(blank=True, help_text='Interview template used for this conversation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='form_ai.interviewform'),
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveIntegerField(help_text='Display order (1, 2, 3, ...)')),
                ('question_text', models.TextField(help_text='Question content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(help_text='Parent interview definition', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='form_ai.interviewform')),
            ],
            options={
                'verbose_name': 'Interview Question',
                'verbose_name_plural': 'Interview Questions',
                'db_table': 'interview_questions',
                'ordering': ['sequence_number'],
                'unique_together': {('form', 'sequence_number')},
            },
        ),
    ]
