# Generated by Django 5.2.6 on 2025-11-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_ai', '0003_interviewform_technicalassessment_interview_form_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(db_index=True, help_text='Role or position (e.g., Python Intern, Backend Developer)', max_length=255)),
                ('sequence_number', models.PositiveIntegerField(help_text='Question order (1, 2, 3...)')),
                ('question_text', models.TextField(help_text='Technical question content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Assessment Question Bank',
                'verbose_name_plural': 'Assessment Question Bank',
                'db_table': 'assessment_question_bank',
                'ordering': ['role', 'sequence_number'],
                'unique_together': {('role', 'sequence_number')},
            },
        ),
    ]
