# Generated by Django 5.2.8 on 2025-11-14 08:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_ai', '0003_interviewform_interviewresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewresponse',
            name='form',
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('questions', models.JSONField()),
                ('messages', models.JSONField(default=list)),
                ('answers', models.JSONField(blank=True, default=dict, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='form_ai.conversation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='InterviewForm',
        ),
        migrations.DeleteModel(
            name='InterviewResponse',
        ),
    ]
