# Generated by Django 5.2.8 on 2025-11-28 05:46

import form_ai.models
from django.db import migrations, models


def copy_text_to_payload(apps, schema_editor):
    """Populate the new JSON payloads with existing question text."""
    payload_builder = form_ai.models.default_question_payload
    question_models = [
        apps.get_model("form_ai", "InterviewQuestion"),
        apps.get_model("form_ai", "AssessmentQuestion"),
        apps.get_model("form_ai", "AssessmentQuestionBank"),
    ]
    for model in question_models:
        for obj in model.objects.iterator():
            text_value = getattr(obj, "question_text", "") or ""
            payload = payload_builder()
            payload["text"] = text_value.strip()
            obj.question_payload = payload
            obj.save(update_fields=["question_payload"])


def restore_text_from_payload(apps, schema_editor):
    """Rebuild legacy text fields if the migration is reversed."""
    question_models = [
        apps.get_model("form_ai", "InterviewQuestion"),
        apps.get_model("form_ai", "AssessmentQuestion"),
        apps.get_model("form_ai", "AssessmentQuestionBank"),
    ]
    for model in question_models:
        for obj in model.objects.iterator():
            payload = getattr(obj, "question_payload", {}) or {}
            text_value = payload.get("text", "")
            if not isinstance(text_value, str):
                text_value = str(text_value or "")
            obj.question_text = text_value.strip()
            obj.save(update_fields=["question_text"])


class Migration(migrations.Migration):

    dependencies = [
        ('form_ai', '0004_assessmentquestionbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentquestion',
            name='question_payload',
            field=models.JSONField(blank=True, default=form_ai.models.default_question_payload, help_text='Normalized question definition stored as JSON (text/type/metadata/options)'),
        ),
        migrations.AddField(
            model_name='assessmentquestionbank',
            name='question_payload',
            field=models.JSONField(blank=True, default=form_ai.models.default_question_payload, help_text='Normalized question definition stored as JSON (text/type/metadata/options)'),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='question_payload',
            field=models.JSONField(blank=True, default=form_ai.models.default_question_payload, help_text='Normalized question definition stored as JSON (text/type/metadata/options)'),
        ),
        migrations.RunPython(copy_text_to_payload, restore_text_from_payload),
        migrations.RemoveField(
            model_name='assessmentquestion',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='assessmentquestionbank',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='interviewquestion',
            name='question_text',
        ),
    ]
