# Generated by Django 5.2.8 on 2025-11-28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("form_ai", "0006_consolidate_question_storage"),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE candidate_answers DROP COLUMN IF EXISTS answered_at;",
            reverse_sql=(
                "ALTER TABLE candidate_answers ADD COLUMN answered_at "
                "timestamp with time zone NULL;"
            ),
        ),
    ]
