# Generated by Django 5.2.6 on 2025-11-30 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_ai', '0007_drop_candidateanswer_answered_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssessmentQuestionBank',
        ),
    ]
