# Generated by Django 5.2.8 on 2025-12-02

from django.db import migrations, models


def migrate_schema_to_questions(apps, schema_editor):
    TechnicalAssessment = apps.get_model("form_ai", "TechnicalAssessment")
    CandidateAnswer = apps.get_model("form_ai", "CandidateAnswer")

    def extract_questions(schema):
        question_texts = []
        normalized_entries = []
        if not isinstance(schema, list):
            return question_texts, normalized_entries

        for entry in schema:
            if isinstance(entry, dict):
                text = (entry.get("text") or entry.get("question") or "").strip()
                sequence = entry.get("sequence_number")
                question_id = entry.get("id")
            else:
                text = (str(entry).strip() if entry is not None else "")
                sequence = None
                question_id = None

            if not text:
                continue

            question_texts.append(text)
            normalized_entries.append(
                {
                    "sequence_number": sequence if sequence else len(question_texts),
                    "id": str(question_id) if question_id else None,
                }
            )
        return question_texts, normalized_entries

    for assessment in TechnicalAssessment.objects.all().iterator():
        question_texts, normalized_entries = extract_questions(
            getattr(assessment, "question_schema", [])
        )
        assessment.questions = question_texts
        assessment.save(update_fields=["questions"])

        if not normalized_entries:
            continue

        try:
            answer_sheet = CandidateAnswer.objects.get(assessment=assessment)
        except CandidateAnswer.DoesNotExist:
            continue

        answers = answer_sheet.answers or {}
        remapped = {}

        for idx, entry in enumerate(normalized_entries, start=1):
            potential_keys = [
                f"q{idx}",
            ]
            legacy_seq = entry.get("sequence_number")
            if legacy_seq:
                potential_keys.append(f"q{legacy_seq}")
            legacy_id = entry.get("id")
            if legacy_id:
                potential_keys.append(legacy_id)

            value = ""
            for key in potential_keys:
                if key in answers and answers[key]:
                    value = answers[key]
                    break

            remapped[f"q{idx}"] = (str(value).strip() or "NIL") if value else "NIL"

        if remapped:
            answer_sheet.answers = remapped
            answer_sheet.save(update_fields=["answers"])


class Migration(migrations.Migration):

    dependencies = [
        ("form_ai", "0008_remove_assessment_question_bank"),
    ]

    operations = [
        migrations.AddField(
            model_name="technicalassessment",
            name="questions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Ordered question text prompts for this assessment",
            ),
        ),
        migrations.RunPython(migrate_schema_to_questions, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="technicalassessment",
            name="question_schema",
        ),
    ]
