# Generated by Django 5.2.8 on 2025-12-02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("form_ai", "0009_remove_assessment_question_schema"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interviewform",
            name="role",
        ),
    ]
