# Generated by Django 5.2.8 on 2025-12-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_ai', '0011_remove_interviewform_summary_ai_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateanswer',
            name='answers',
            field=models.JSONField(blank=True, default=dict, help_text='Question key (e.g., q1, q2) mapped to normalized answer text'),
        ),
    ]
