# Generated by Django 5.2.8 on 2025-12-03 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_ai', '0014_interviewresponse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewresponse',
            options={'verbose_name': 'Interview Response', 'verbose_name_plural': 'Interview Responses'},
        ),
    ]
