# Generated by Django 5.2.8 on 2025-12-05 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_ai', '0015_alter_interviewresponse_options'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE voice_conversations
                ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
            """,
            reverse_sql="""
                ALTER TABLE voice_conversations
                DROP COLUMN IF EXISTS created_at;
            """,
        ),
        migrations.RunSQL(
            sql="""
                UPDATE voice_conversations
                SET created_at = COALESCE(created_at, NOW())
                WHERE created_at IS NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE voice_conversations
                ALTER COLUMN created_at SET DEFAULT NOW();
            """,
            reverse_sql="""
                ALTER TABLE voice_conversations
                ALTER COLUMN created_at DROP DEFAULT;
            """,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE voice_conversations
                ALTER COLUMN created_at SET NOT NULL;
            """,
            reverse_sql="""
                ALTER TABLE voice_conversations
                ALTER COLUMN created_at DROP NOT NULL;
            """,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE voice_conversations
                ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
            """,
            reverse_sql="""
                ALTER TABLE voice_conversations
                DROP COLUMN IF EXISTS updated_at;
            """,
        ),
        migrations.RunSQL(
            sql="""
                UPDATE voice_conversations
                SET updated_at = COALESCE(updated_at, NOW())
                WHERE updated_at IS NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE voice_conversations
                ALTER COLUMN updated_at SET DEFAULT NOW();
            """,
            reverse_sql="""
                ALTER TABLE voice_conversations
                ALTER COLUMN updated_at DROP DEFAULT;
            """,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE voice_conversations
                ALTER COLUMN updated_at SET NOT NULL;
            """,
            reverse_sql="""
                ALTER TABLE voice_conversations
                ALTER COLUMN updated_at DROP NOT NULL;
            """,
        ),
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1
                        FROM pg_indexes
                        WHERE schemaname = current_schema()
                          AND indexname = 'voice_conversations_created_at_idx'
                    ) THEN
                        CREATE INDEX voice_conversations_created_at_idx
                        ON voice_conversations (created_at DESC);
                    END IF;
                END
                $$;
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS voice_conversations_created_at_idx;
            """,
        ),
    ]
