# Generated by Django 5.2.8 on 2025-12-05 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_ai', '0016_add_missing_voice_conversation_timestamps'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE interview_responses
                ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
            """,
            reverse_sql="""
                ALTER TABLE interview_responses
                DROP COLUMN IF EXISTS created_at;
            """,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE interview_responses
                ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
            """,
            reverse_sql="""
                ALTER TABLE interview_responses
                DROP COLUMN IF EXISTS updated_at;
            """,
        ),
    ]
