# Generated by Django 5.2.8 on 2025-12-05 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_ai', '0017_add_missing_interview_response_timestamps'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE voice_conversations
                DROP COLUMN IF EXISTS transcript_text;
            """,
            reverse_sql="""
                ALTER TABLE voice_conversations
                ADD COLUMN IF NOT EXISTS transcript_text TEXT NOT NULL DEFAULT '';
            """,
        ),
    ]
